language: python
python:
  - "3.5"
  - "3.6"

# command to install dependencies
install:
    - pip install -r requirements.txt
    - python setup.py install

script:
    - pip install -r requirements.txt
    - pip install nose
    - nosetests -v ripple/tests/
